#cloud-config
rancher:
  network:
    interfaces:
      eth0:
        dhcp: true
  system_docker:
    userland_proxy: true
    environment:
      - HTTP_PROXY=10.215.41.71:8080
      - HTTPS_PROXY=10.215.41.71:8080
      - NO_PROXY=localhost,127.0.0.1,10.215.*
  docker:
    environment:
    - HTTP_PROXY=10.215.41.71:8080
    - HTTPS_PROXY=10.215.41.71:8080
    - NO_PROXY=localhost,127.0.0.1,10.215.*
  ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCtMWk/cRxcrlCiHK07p7QHRBPXX18IO2KI5kmC3iCKlzNGOHm4pUQIskK6G4hgok4HzkjYOFOBp3o3kv0x4SnA1JHk5XHvX8pP/7CZuH9KIxi60jYac55IdwnNCpxKF0fBeZiyI96BxffynRLEXwjZwFPKlsk7+pNjr0H3Yhr8jidWn3qwGwQ++3WhPqOsJnTv/3ZXYMhqDJCS9FvWt4cfPF44RN+Wwsuzg/DdgX6vX+X7yeq1unkgQi7XgIYsv/aXHolEG47SpI38/F5ZVoCKbd7/yhlBEgSYQC/3f7bYCjJ1laQXk5AS3OwRL4OhLPooYy92GAbQLTJVx8+vGFH2WEYRwt/mUYptb26sq2ZqnWAwePPhbeEWYV0/HtYP451PgmXqJBuIWEym82IqHPk5S8UnC7C0M5psZSzZ6Br9kC8rvnh+LDikPCYI1vS3EjSkoWqRv+0npv4pEdobyYxahUEN5caPiiEqyBJaJLhXJTCxCSj8SDgUU0ystCW7CX24FTUc3AaKZJY+c84D0G2rtutbxD2C7n7GRluffA94W7WuXi1c9AzaPW6xpl33xsoIHTKXpN8+mCV7czDBQXyUr03JUXhBNtKBJgFaeat6k6+25Ej5yVcWCe0Z7WtBC0Jj3lmPPFZ3d6f8xnfB0hVh5EmAzwEK+jXwVFeqycRaPQ== me@debian.local

    
